name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y shellcheck
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install shellcheck
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install -y shellcheck make mingw
            echo "C:\\tools\\mingw64\\bin" >> "$GITHUB_PATH"
            echo "C:\\ProgramData\\chocolatey\\lib\\make\\tools\\GnuWin32\\bin" >> "$GITHUB_PATH"
          fi
      - name: Lint Shell Scripts
        run: shellcheck tests/*.sh
      - name: Build
        run: make
      - name: Test
        run: make test
