name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Lint Shell Scripts
        run: shellcheck tests/*.sh
      - name: Build
        run: make
      - name: Test
        run: make test
